# Generated by Django 4.2.21 on 2026-08-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_trackedpricehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackedpricehistory',
            name='product',
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
        migrations.DeleteModel(
            name='TrackedPriceHistory',
        ),
    ]
