# Generated by Django 4.2.21 on 2026-08-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_trackedpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_tracking',
            field=models.BooleanField(default=True),
        ),
    ]
