# Generated by Django 4.2.21 on 2026-08-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_product_is_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
