# Generated by Django 4.2.21 on 2026-08-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_product_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedproduct',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
